version: '3.4'

services:
    plots: &plots
        image: chia
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - /g-plots/plots:/plots
            - /home/aarmcm/.chia/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chia-plots:/home/chia/.chia
        environment:
            harvester: "true"
            keys: copy
            farmer_address: 192.168.2.94
            farmer_port: 8447
            ca: /ca
            log_level: INFO

    plots2:
        <<: *plots
        volumes:
            - /g-plots/plots2:/plots
            - /home/aarmcm/.chia/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chia-plots2:/home/chia/.chia

    plots3:
        <<: *plots
        volumes:
            - /g-plots/plots3:/plots
            - /home/aarmcm/.chia/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chia-plots3:/home/chia/.chia

    plots4:
        <<: *plots
        volumes:
            - /g-plots/plots4:/plots
            - /home/aarmcm/.chia/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chia-plots4:/home/chia/.chia
