version: '3.4'

# Full node + harvesters

volumes:
    sekrit:

services:
    fullnode:
        build: .
        image: silicoin
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "6885:6885"
            - "6888:6888"
        volumes:
            - sekrit:/home/silicoin/.local
            - /mnt/chia_plots/0:/chia_plots0
            - /mnt/chia_plots/1:/chia_plots1
            - /home/user/.silicoin:/home/silicoin/.chia
        environment:
            keys: none
            log_level: INFO
            plots_dir: /chia_plots0:/chia_plots1
        # Make interactive -- Attach to provide keys
        stdin_open: true
        tty: true

    plots: &plots
        image: silicoin
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - /mnt/plots:/plots
            - /home/user/.silicoin/mainnet/config/ssl/ca:/ca
            - /home/user/.silicoin-plots:/home/silicoin/.chia
        environment: &env
            harvester: "true"
            keys: copy
            farmer_address: fullnode
            farmer_port: 6885
            ca: /ca
            log_level: INFO

    plots2:
        <<: *plots
        volumes:
            - /mnt/plots2:/plots
            - /home/user/.silicoin/mainnet/config/ssl/ca:/ca
            - /home/user/.silicoin-plots2:/home/silicoin/.chia
