version: '3.4'

volumes:
    sekrit:

services:
    fullnode:
        build:
            context: .
        image: mass
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "43453:43453"  # Miner
            - "43454:43454"  # Wallet
            - "9690:9690"    # pool port for fractal miners to connect to
        volumes:
            - sekrit:/home/mass/.local
            - /mnt/plots:/plots
            - /home/user/.mass:/home/mass/.mass
        environment:
            payout_address: ms1qqz5sy0w8e70m0np4a0hxs43a2m79e3j6pjq80qjmga7a7c2dlxsjqmtg3vp
            mode: collector  # Delete this line if not running fractal miners
        # Make interactive
        stdin_open: true
        tty: true

    # Only use one fullnode or fractal
    fractal:
        build:
            context: .
        image: mass
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - sekrit:/home/mass/.local
            - /mnt/plots:/plots
            - /home/user/.mass:/home/mass/.mass
        environment:
            mode: fractal
            miner_ip_port: 10.10.1.1:9690  # Fill in with real LAN ip for fullnode
        # Make interactive
        stdin_open: true
        tty: true
