version: '3.4'

volumes:
    sekrit:

services:
    fullnode:
        build:
            context: .
        image: mass
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "43453:43453"  # Miner
        volumes:
            - sekrit:/home/mass/.local
            - /mnt/plots:/plots
            - /home/user/.mass:/home/mass/.mass
        environment:
            keys: none
            log_level: INFO
            payout_address: ms1qqz5sy0w8e70m0np4a0hxs43a2m79e3j6pjq80qjmga7a7c2dlxsjqmtg3vp
        # Make interactive
        stdin_open: true
        tty: true
