version: '3.4'

volumes:
    sekrit:

services:
    fullnode:
        build:
            context: .
            args:
              - BRANCH=1.2.1
        image: chaingreen
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "8744:8744"  # Node
            - "8777:8777"  # Farmer
        volumes:
            - sekrit:/home/chaingreen/.local
            - /mnt/chia_plots/0:/chia_plots0
            - /mnt/chia_plots/1:/chia_plots1
            - /mnt/mobile_plots/10:/mobile_plots10
            - /home/aarmcm/.chaingreen:/home/chaingreen/.chaingreen
        environment:
            keys: none
            log_level: INFO
            node: "false"  # Run the farmer now
            plots_dir: /chia_plots0:/chia_plots1:/mobile_plots10
        # Make interactive -- Attach to provide keys
        stdin_open: true
        tty: true

    plots: &plots
        image: chaingreen
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - /g-plots/plots:/plots
            - /home/aarmcm/.chaingreen/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chaingreen-plots:/home/chaingreen/.chaingreen
        environment:
            harvester: "true"
            keys: copy
            farmer_address: fullnode
            farmer_port: 8777
            ca: /ca
            log_level: INFO

    plots2:
        <<: *plots
        volumes:
            - /g-plots/plots2:/plots
            - /home/aarmcm/.chaingreen/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chaingreen-plots2:/home/chaingreen/.chaingreen

    plots3:
        <<: *plots
        volumes:
            - /g-plots/plots3:/plots
            - /home/aarmcm/.chaingreen/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chaingreen-plots3:/home/chaingreen/.chaingreen

    plots4:
        <<: *plots
        volumes:
            - /g-plots/plots4:/plots
            - /home/aarmcm/.chaingreen/mainnet/config/ssl/ca:/ca
            - /home/aarmcm/.chaingreen-plots4:/home/chaingreen/.chaingreen
