version: '3.4'

volumes:
    sekrit:

services:
    fullnode:
        build:
            context: .
            args:
              - BRANCH=1.2.1
        image: chaingreen
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "8744:8744"  # Node
            - "8777:8777"  # Farmer
        volumes:
            - sekrit:/home/chaingreen/.local
            - /mnt/chia_plots/0:/chia_plots0
            - /mnt/chia_plots/1:/chia_plots1
            - /home/user/.chaingreen:/home/chaingreen/.chaingreen
        environment:
            keys: none
            log_level: INFO
            plots_dir: /chia_plots0:/chia_plots1
            satellite_region: "${satellite_region:-us}"
            satellite_key: ""
        # Make interactive -- Attach to provide keys
        stdin_open: true
        tty: true

    plots: &plots
        image: chaingreen
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - /mnt/plots:/plots
            - /home/user/.chaingreen/mainnet/config/ssl/ca:/ca
            - /home/user/.chaingreen-plots:/home/chaingreen/.chaingreen
        environment:
            harvester: "true"
            keys: copy
            farmer_address: fullnode
            farmer_port: 8777
            ca: /ca
            log_level: INFO
            satellite_region: "${satellite_region:-us}"
            satellite_key: ""

    plots2:
        <<: *plots
        volumes:
            - /mnt/plots2:/plots
            - /home/user/.chaingreen/mainnet/config/ssl/ca:/ca
            - /home/user/.chaingreen-plots2:/home/chaingreen/.chaingreen
