version: '3.4'

# Full node + harvesters

volumes:
    sekrit:

services:
    fullnode:
        build: .
        image: chives
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "9699:9699"  # Node
            - "9647:9647"  # Farmer
        volumes:
            - sekrit:/home/chives/.local
            - /mnt/plots/chives:/plots
            - /home/user/.chives:/home/chives/.chives
        environment:
            keys: none
            log_level: INFO
        # Make interactive -- Attach to provide keys
        stdin_open: true
        tty: true

    plots: &plots
        image: chives
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - /mnt/plots:/plots
            - /home/user/.chives/mainnet/config/ssl/ca:/ca
            - /home/user/.chives-plots:/home/chives/.chives
        environment: &env
            harvester: "true"
            keys: copy
            farmer_address: fullnode
            farmer_port: 9647
            ca: /ca
            log_level: INFO

    plots2:
        <<: *plots
        volumes:
            - /mnt/plots2:/plots
            - /home/user/.chives/mainnet/config/ssl/ca:/ca
            - /home/user/.chives-plots2:/home/chives/.chives
        environment:
            <<: *env
