version: '3.4'

# Full node + harvesters

volumes:
    sekrit:

services:
    fullnode:
        build: .
        image: staicoin
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "6885:6885"
            - "6888:6888"
        volumes:
            - sekrit:/home/staicoin/.local
            - /mnt/chia_plots/0:/chia_plots0
            - /mnt/chia_plots/1:/chia_plots1
            - /home/user/.staicoin:/home/staicoin/.staicoin
        environment:
            keys: none
            log_level: INFO
            plots_dir: /chia_plots0:/chia_plots1
            satellite_region: "${satellite_region:-us}"
            satellite_key: ""
        # Make interactive -- Attach to provide keys
        stdin_open: true
        tty: true

    plots: &plots
        image: staicoin
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - /mnt/plots:/plots
            - /home/user/.staicoin/mainnet/config/ssl/ca:/ca
            - /home/user/.staicoin-plots:/home/staicoin/.staicoin
        environment: &env
            harvester: "true"
            keys: copy
            farmer_address: fullnode
            farmer_port: 6885
            ca: /ca
            log_level: INFO
            satellite_region: "${satellite_region:-us}"
            satellite_key: ""

    plots2:
        <<: *plots
        volumes:
            - /mnt/plots2:/plots
            - /home/user/.staicoin/mainnet/config/ssl/ca:/ca
            - /home/user/.staicoin-plots2:/home/staicoin/.staicoin
        environment:
            <<: *env
            satellite_key: ""
