version: '3.4'

# Full node + harvesters

volumes:
    sekrit:

services:
    fullnode:
        build: .
        image: petroleum
        user: "${CURRENT_UID:-1000:1000}"
        ports:
            - "33344:33344"
            - "33347:33347"
        volumes:
            - sekrit:/home/petroleum/.local
            - /mnt/chia_plots/0:/chia_plots0
            - /mnt/chia_plots/1:/chia_plots1
            - /home/user/.petroleum:/home/petroleum/.petroleum
        environment:
            keys: none
            log_level: INFO
            plots_dir: /chia_plots0:/chia_plots1
        # Make interactive -- Attach to provide keys
        stdin_open: true
        tty: true

    plots: &plots
        image: petroleum
        user: "${CURRENT_UID:-1000:1000}"
        volumes:
            - /mnt/plots:/plots
            - /home/user/.petroleum/mainnet/config/ssl/ca:/ca
            - /home/user/.petroleum-plots:/home/petroleum/.petroleum
        environment: &env
            harvester: "true"
            keys: copy
            farmer_address: fullnode
            farmer_port: 33347
            ca: /ca
            log_level: INFO

    plots2:
        <<: *plots
        volumes:
            - /mnt/plots2:/plots
            - /home/user/.petroleum/mainnet/config/ssl/ca:/ca
            - /home/user/.petroleum-plots2:/home/petroleum/.petroleum
        environment:
            <<: *env
